---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Ruff - Python linter and formatter (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Use the latest version from https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # Taplo - TOML formatter and linter
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3  # Use the latest version from https://github.com/ComPWA/taplo-pre-commit/releases
    hooks:
      - id: taplo-format
      - id: taplo-lint

  # yamllint - YAML linter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1  # Use the latest version from https://github.com/adrienverge/yamllint/releases
    hooks:
      - id: yamllint
        args: [--strict, --config-file=.yamllint]

  # Pyright - Python type checker
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406  # Use the latest version from https://github.com/RobertCraigie/pyright-python/releases
    hooks:
      - id: pyright

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
